[IV-23-23] Objetivo 3
chelunike/didactic-chainsaw pull request #16
Opened 2023-12-13 18:59 UTC by chelunike

* [x] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x] ¿Ese issue está asignado a un milestone?
* [x] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [x] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [x] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [x] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-12-15 06:56 UTC, chelunike commented
Revisores → @Enaraque @adelahera @moshidev @MarioGuisado @raultl12

2023-12-17 20:50 UTC, moshidev approved these changes
👍 cuidado con las erratas.

2023-12-18 17:52 UTC, JJ commented
Por favor, @raultl12, ¿podrías echarle un vistazo?

2023-12-19 09:14 UTC, raultl12 commented
En general lo veo bien, aunque descartar opciones de runtime solo porque la empresa te caiga mal o porque te de miedo no creo que sean razones de peso. Creo que no debemos dejar que las emociones guíen nuestras decisiones técnicas. Intenta dar otros motivos por los que descartar Amazon e IMB (revisa también otras decisiones). También he encontrado alguna errata en el archivo gestor_dependencias.md.

2023-12-19 09:20 UTC, chelunike commented
> En general lo veo bien, aunque descartar opciones de runtime solo porque la empresa te caiga mal o porque te de miedo no creo que sean razones de peso. Creo que no debemos dejar que las emociones guíen nuestras decisiones técnicas. Intenta dar otros motivos por los que descartar Amazon e IBM (revisa también otras decisiones). También he encontrado alguna errata en el archivo gestor_dependencias.md.

Esas razones son más de índole personal y de poco peso, la importante es que no voy a usar ninguna de las plataformas de esas empresas, por lo cual no requiere de esa optimización.

2023-12-19 09:23 UTC, JJ commented
@raultl12 por favor, aprueba explícitamente si lo ves bien. En general, estoy de acuerdo contigo, sólo que a @chelunike le diría que tratara de poner condiciones "a priori" para la elección, como la licencia de los runtimes, por ejemplo, o la razón técnica o de licencias por la que no está de acuerdo con la empresa.

2023-12-19 09:27 UTC, raultl12 approved these changes

2023-12-20 06:48 UTC, JJ requested changes
El problema principal es que no has implementado el `check`, que era uno de los objetivos. Trata de revisar cuidadosamente los objetivos de aprendizaje, y revisa también lo que te han comentado. Gracias a @moshidev por sus comentarios.

2023-12-20 06:48 UTC, JJ commented on README.md
> +- WIP: Instrucciones de instalación de Java y Gradle
Esto deberías completarlo antes de fusionar.

2023-12-20 06:48 UTC, JJ commented on build.gradle
> +tasks.named('test') {
La única tarea que hay que hacer es `check`, que compruebe la sintaxis.

2023-12-20 06:48 UTC, JJ commented on README.md
> +`./gradlew check`
Yo diría que esta tarea no está codificada, salvo que lo esté por omisión.

2023-12-20 06:48 UTC, JJ commented on iv.yaml
> +  fichero: gradlew
¿Seguro que este es el fichero? ¿No será settings.gradle?

2023-12-20 06:48 UTC, JJ commented on docs/runtime.md
> +Original de la casa de Oracle, es una versión que funciona de igual manera para todos, sin ninguna optimización respecto a la plataforma. En este caso solo se reciben actualizaciones cada 6 meses y l
No estás exponiendo en cada uno de ellos si siguen o no los criterios.

2023-12-20 06:48 UTC, JJ commented on docs/runtime.md
> +Esta versión obra de Amazon está optimizada en rendimiento para funcionar mejor en los servidores de AWS, de forma que permite una mejor gestión de recursos si se despliega en esta plataforma.
Enlaza también de dónde se pueden descargar cada uno doe ellos.

2023-12-20 06:48 UTC, JJ commented on docs/runtime.md
> +- BellSoft su traducción literal seria `Campana programa`, me gustan las campanas.
Esto está bien, pero no has dicho si va a ser viable en los próximos años, que es tu criterio de elección.

2023-12-21 09:10 UTC, chelunike commented on README.md
> +`./gradlew check`
Ya se encuentra declarara `gradle check` y lo que realiza es una comprobación del código y de que encuentre todas las librerias. También se puede añadir un plugin [Check Style](https://docs.gradle.org/current/userguide/checkstyle_plugin.html) que va mas alla y realiza otras comprobaciones.

2023-12-21 11:32 UTC, JJ commented on README.md
> +`./gradlew check`
No es eso lo que pide el objetivo, sino que la sintaxis del código sea correcta, *y solo eso*. Por favor, trata de seguir el guión.

2023-12-22 11:43 UTC, chelunike commented on README.md
> +- WIP: Instrucciones de instalación de Java y Gradle
Ya esta creada la documentación

2023-12-22 11:47 UTC, chelunike commented on iv.yaml
> +  fichero: gradlew
En realidad es `build.gradle` que realimente contiene toda la info. Ya esta modifcada.

2023-12-25 08:35 UTC, JJ commented
Perdona que te moleste, pero sería conveniente que trataras de resolver esto como hablamos en clase, y cuanto antes mejor, para que puedas pasar al siguiente objetivo.

2023-12-26 12:58 UTC, chelunike commented on docs/runtime.md
> +Original de la casa de Oracle, es una versión que funciona de igual manera para todos, sin ninguna optimización respecto a la plataforma. En este caso solo se reciben actualizaciones cada 6 meses y l
Ya estan añadida la explicación de cada uno si siguen los criterios.

2023-12-26 12:58 UTC, chelunike commented on docs/runtime.md
> +- BellSoft su traducción literal seria `Campana programa`, me gustan las campanas.
He extendido la expliación con los detalles de cada uno.

2023-12-26 20:26 UTC, chelunike commented on docs/runtime.md
> +Esta versión obra de Amazon está optimizada en rendimiento para funcionar mejor en los servidores de AWS, de forma que permite una mejor gestión de recursos si se despliega en esta plataforma.
También he puesto los enlaces de descarga.

2023-12-28 18:31 UTC, JJ commented
Por favor, avísame por aquí cuando esté listo para revisión.

2024-01-01 16:42 UTC, chelunike commented on build.gradle
> +tasks.named('test') {
Ya he creado la task `check-code`para comprobarlo.

2024-01-01 16:42 UTC, chelunike commented on README.md
> +`./gradlew check`
Ya he creado la task `check-code` para comprobarlo.

2024-01-01 16:43 UTC, chelunike commented
@JJ  Listo para revisión :+1:

2024-01-01 18:54 UTC, JJ approved these changes
:+1:

2024-01-01 19:17 UTC, merged