Objetivo 1 - IV 23/24
chelunike/didactic-chainsaw pull request #3
Opened 2023-09-22 12:11 UTC by chelunike

Creado primer historia de usuario y mileston

2023-09-22 12:15 UTC, chelunike commented
Milestones

* [x] ¿Las historias de usuario y los milestones constituyen una guía suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o 0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en clase, y en concreto con lo que se solicita en el objetivo siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el contrario podrían desarrollarse muchas posibles etapas internas o externas de un proyecto?

Historias de Usuario

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso de que no lo tengan, se ha escrito un *user journey* para  aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-29 11:33 UTC, puchy22 commented
@chelunike En el README solo aparece un milestone, creo que te has olvidado de incluirlo ya que en el repositorio sí que está.

2023-09-29 11:35 UTC, chelunike commented
@puchy22 Ya esta reflejado el 2 milestone en el README.md. :+1:

2023-09-29 12:03 UTC, puchy22 reviewed
He puesto algunos cambios que creo que serían necesarios para avanzar al siguiente objetivo, espero que te ayuden :memo:

2023-09-29 12:03 UTC, puchy22 commented on docs/README.md
> +El programa en si mismo buscara los CVES de forma externa, procesara la información y luego presentara los resultados al usuario.
Esta descripción no es la de un producto, en los milestones hay que describir un PMV qué sería un entregable para el cliente final. Creo que estaría bien que revisases este documento recomendado por el profesor para entender bien los PMV https://jj.github.io/IV/preso/pmv.html

2023-09-29 17:30 UTC, adelahera commented
> He puesto algunos cambios que creo que serían necesarios para avanzar al siguiente objetivo, espero que te ayuden 📝

Hola, yo soy otro de tus revisores. De momento, apoyo todos los cambios que ha sugerido @puchy22. Cuando hagas un nuevo commit lo revisaré de nuevo. Por añadir algo, creo que deberías prestar más cuidado a los errores ortográficos, he visto unos pocos. De momento no te los marco porque entiendo que vas a rehacerlo de nuevo y supongo que lo arreglarás.

2023-10-05 11:02 UTC, JJ commented
Por favor, la lista de comprobación tiene que ir en el cuerpo del PR

2023-10-17 08:59 UTC, JJ commented
¿Vas a seguir adelante con esto? ¿Algún problema?

2023-10-17 11:07 UTC, chelunike commented
Lamento no haber trabajado antes en ello, pero llevo un par de semanas liado con más proyectos. He replanteado por completo los Milestones, espero haber comprendido esta vez mejor la metodologia.

2023-10-20 11:08 UTC, chelunike commented
Mis revisores oficiales son: @danieeeld2 @adelahera @LuciaAnsino @Morad02 @manuelvico0102

2023-10-20 11:25 UTC, manuelvico0102 requested changes

2023-10-20 11:25 UTC, manuelvico0102 commented on docs/README.md
> +
En los milestones te aconsejo dejar claro para cada uno cuál es el objetivo del milestone, lo que se debería entregar y que lo hace viable

2023-10-20 11:25 UTC, manuelvico0102 commented on docs/README.md
> +
Las historias de usuario son utilizadas para poder empezar con la modelización del problema, por lo que te aconsejo añadir más contexto. Ya que con las historias de usuario ya se debería entender todo el problema como que datos se van a utilizar.

2023-10-20 11:40 UTC, chelunike commented on docs/README.md
> +
Has mencionado parte de la historia de usuario, te refieres a que los milestiones en general sean mas breves y concisos.

2023-10-20 11:42 UTC, chelunike commented on docs/README.md
> +
Creo que no estoy viendo que datos son los que faltan. ¿Podrias especificar algun dato especifo que falta que sea relevante?

2023-10-21 09:42 UTC, manuelvico0102 commented on docs/README.md
> +
No, es que tengan que ser más breve o no, pero tienen que dejar claro cuál es el objetivo, que haría viable al milestone y que se debe entregar para cumplir el objetivo. En este caso yo creo que el objetivo de cada milestone está claro, pero te faltaría concretar lo demás.

2023-10-21 09:42 UTC, manuelvico0102 commented on docs/README.md
> +
En la historia de usuario mencionas "Es un gran problema el tener que procesar de forma manual tanta información a la vez". Pienso que deberías concretar cuál es esa información, ya que para el siguiente objetivo la persona que tenga que trabajar con tu repositorio no sepa cuál es esa información, así que sería aconsejable que la indicases de forma más clara.

2023-10-21 09:52 UTC, adelahera reviewed
Buenas. Creo que has mejorado bastante respecto a la última vez. Aun así, hay un par de cosas que quizá podrías mejorar. Primero, en cuanto a la historia de usuario, deberías explicar un poco mejor que es lo quiere el usuario en cuestión, a mí al menos no me ha quedado muy claro (quizá sea porque no estoy muy metido en ese tema, y no tengo ni idea de qué es un cve, por ejemplo). Creo que deberías intentar redactarlo mejor, para facilitar lo máximo posible la tarea a la persona que luego realizará el objetivo 2.

Sobre los milestones, los veo correctos, pero debes incluir cuál va a ser tu PMV para cada uno ellos.

2023-10-23 15:01 UTC, chelunike commented on docs/README.md
> +
He puesto más detalles respecto al problema, ¿ahora se entiende mejor?

2023-10-27 08:03 UTC, chelunike commented on docs/README.md
> +La respuesta deberá contener tanto el codigo que identifica el CVE, nombre/titulo que casi siempre resume por completo el modo en que se aprovecha la vulnerabilidad y un enlace a la descripción y al
@puchy22 Arreglado en el siguiente commit :)

2023-10-27 08:04 UTC, chelunike commented on docs/README.md
> +2. [MI002] Logica de Negocio
@puchy22 Arreglado en el siguiente commit :)

2023-10-27 08:04 UTC, chelunike commented on docs/README.md
> +2. [MI001] Modelo del Problema
@puchy22 Arreglado en el siguiente commit :)

2023-10-27 08:04 UTC, chelunike commented on docs/README.md
> +En medio de un CTF, cuando se intenta de forma ágil resolver un problema planteado, solo que de este problema solo hay ciertas pistas y tienes que buscar una flag. En el momento en el que se requiere
@puchy22 Arreglado en el siguiente commit :)

2023-10-27 10:50 UTC, manuelvico0102 requested changes
Te faltaría arreglar lo de los milestone y creo que ya podría el profesor pasar a revisarlo

2023-10-27 10:50 UTC, manuelvico0102 commented on docs/README.md
> +
Vale, yo creo que con esto puede ser suficiente.

2023-10-27 10:50 UTC, manuelvico0102 commented on docs/README.md
> +
Aún te faltaría realizar el cambio de los milestones con lo que te indique.

2023-10-27 11:02 UTC, chelunike commented
@manuelvico0102 He agregado la especificación del PMV a cada milestone, ¿asi queda más claro que hacer para cada objetivo?

2023-10-27 11:13 UTC, manuelvico0102 requested changes

2023-10-27 11:13 UTC, manuelvico0102 commented on docs/README.md
> +:cat2:
Lo que has añadido lo veo bien, sin embargo aun no has mencionado que lo haría viable por ejemplo podría ser que el milestone sería viable si el product manager lo aprueba o sería viable si se logran pasar los tests. Esto ya dependerá de cada milestone, pero es importante que menciones esto.

2023-10-27 11:18 UTC, chelunike commented on docs/README.md
> +:cat2:
@manuelvico0102  Ya he agregado ese detalle a los milestones, creo que esta listo para que @JJ  lo revise.

2023-10-27 11:24 UTC, manuelvico0102 approved these changes
Yo creo que ya esta listo para que lo revise @JJ

2023-10-27 11:51 UTC, JJ requested changes
Ánimo, ya te queda menos. Muchas gracias a @manuelvico0102 @adelahera y @puchy22  por la colaboración

2023-10-27 11:51 UTC, JJ commented on docs/README.md
> +2. [MI1] Recepción de CVEs
El M1 *siempre* es la lógica de negocio en parte o completa en esta asignatura.

2023-10-27 11:55 UTC, chelunike commented on docs/README.md
> +2. [MI1] Recepción de CVEs
@JJ  Replanteado Milestone haciendo referencia a la lógica de negocio principal que es la extracción de información de los  CVEs

2023-10-27 15:27 UTC, JJ approved these changes
Voy a aprobar porque las fechas son ya un poco tardías y deberías ponerte inmediatamente con el objetivo 2; pero el PMV del objetivo 1 deberías especificarlo un poco más más adelante.

2023-10-27 15:27 UTC, JJ commented on docs/README.md
> +### Milestone
¿Sería plural, no?

2023-10-27 15:27 UTC, JJ commented on docs/README.md
> +PMV: API o Web Scrapper que sea capaz de recabar todos los datos de los CVEs actuales y antiguos.
API o Web scraper son cosas muy diferentes, deberías afinar un poco más lo que vas a hacer exactamente.

2023-11-02 07:40 UTC, chelunike commented on docs/README.md
> +PMV: API o Web Scrapper que sea capaz de recabar todos los datos de los CVEs actuales y antiguos.
@JJ La cuestión es que todavía no se exactamente el sitio del cual extraer los datos y dependiendo de uno u otro es una cosa diferente.

2023-11-02 07:42 UTC, chelunike commented on docs/README.md
> +### Milestone
Si, corregido :)

2023-11-02 07:44 UTC, JJ commented on docs/README.md
> +PMV: API o Web Scrapper que sea capaz de recabar todos los datos de los CVEs actuales y antiguos.
El producto que hagas no tiene nada que ver con la fuente; es lo que tú vas a publicar.

2023-11-02 08:21 UTC, chelunike commented on docs/README.md
> +PMV: API o Web Scrapper que sea capaz de recabar todos los datos de los CVEs actuales y antiguos.
Ok, se plantea el producto como una libreria para extraer los datos.

2023-11-02 08:25 UTC, JJ approved these changes
👍

2023-11-02 08:27 UTC, merged